### ISSUE TITLE
Turning off not working on real hardware

### ISSUE THREAD

**Issue by Clanmaster21** [Clanmaster21/1337OS#9]
Command 2, turning off, no longer works on real hardware. it seems to jump straight back to the main os loop. This indicates int 0x15 is failing to work as intended.

**Comment by Clanmaster21** [comment]
Error code is 0x03 in ah, "Interface not connected"

**Comment by Clanmaster21** [comment]
Fixed, somehow the line "mov ax, 0x5301" (the input for int 0x15 to connect the real mode interface) had become "mov ax, 0x530", will be pushed in next update. It's a wonder it still worked on the virtual machine.

**Comment by yur3i** [comment]
lol, ur so bad, how did you not see that?

**Comment by yur3i** [comment]
cuz im better than u

**Comment by Clanmaster21** [comment]
Install my OS or get out
